-- MySQL Script generated by MySQL Workbench
-- Wednesday, 15 November, 2023 09:45:25 PM PST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Sales_Payment_And_Receivables
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sales_Payment_And_Receivables
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sales_Payment_And_Receivables` DEFAULT CHARACTER SET utf8 ;
USE `Sales_Payment_And_Receivables` ;

-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`supplier` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`supplier` (
  `name` VARCHAR(45) NULL,
  `streetno` VARCHAR(45) NULL,
  `streetname` VARCHAR(45) NULL,
  `barangay` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `estabyear` DATE NULL,
  `subdname` VARCHAR(45) NULL,
  `supplierid` INT(4) NOT NULL,
  PRIMARY KEY (`supplierid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`ref_coldays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`ref_coldays` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`ref_coldays` (
  `day` INT(2) NOT NULL,
  PRIMARY KEY (`day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`person` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`person` (
  `personid` INT(4) NOT NULL,
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  PRIMARY KEY (`personid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`Customer` (
  `customerid` INT(4) NOT NULL,
  `personid` INT(4) NULL,
  PRIMARY KEY (`customerid`),
  INDEX `FK06002_idx` (`personid` ASC),
  CONSTRAINT `FK06002`
    FOREIGN KEY (`personid`)
    REFERENCES `Sales_Payment_And_Receivables`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`products` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`products` (
  `productnum` INT(4) NOT NULL,
  `product_type` ENUM('F', 'NF') NOT NULL,
  `productprice` INT(6) NULL,
  `product_supply` INT(6) NULL,
  `supplierid` INT(6) NULL,
  `status` ENUM('S', 'NS', 'D') NULL,
  `revenueearned` INT(6) NULL,
  PRIMARY KEY (`productnum`),
  CONSTRAINT `FK04001`
    FOREIGN KEY ()
    REFERENCES `Sales_Payment_And_Receivables`.`supplier` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`sales_rep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`sales_rep` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`sales_rep` (
  `salesrepid` INT(4) NOT NULL,
  `personid` INT(4) NULL,
  `totalsales` VARCHAR(45) NULL,
  `supplierid` INT(4) NULL,
  PRIMARY KEY (`salesrepid`),
  INDEX `FK02001_idx` (`personid` ASC),
  INDEX `FK02002_idx` (`supplierid` ASC),
  CONSTRAINT `FK02001`
    FOREIGN KEY (`personid`)
    REFERENCES `Sales_Payment_And_Receivables`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK02002`
    FOREIGN KEY (`supplierid`)
    REFERENCES `Sales_Payment_And_Receivables`.`supplier` (`supplierid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`invoice` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`invoice` (
  `invoicenum` INT(4) NOT NULL,
  `productid` INT(4) NULL,
  `quantity` INT(6) NULL,
  `totalamountofpayment` INT(6) NULL,
  `status` ENUM('P', 'NP', 'D') NULL,
  `salesrepid` INT(4) NULL,
  `customerid` INT(4) NULL,
  PRIMARY KEY (`invoicenum`),
  INDEX `FK20001_idx` (`salesrepid` ASC),
  CONSTRAINT `FK20001`
    FOREIGN KEY (`salesrepid`)
    REFERENCES `Sales_Payment_And_Receivables`.`sales_rep` (`salesrepid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sales_Payment_And_Receivables`.`Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sales_Payment_And_Receivables`.`Payment` ;

CREATE TABLE IF NOT EXISTS `Sales_Payment_And_Receivables`.`Payment` (
  `paymentid` INT(4) NOT NULL,
  `amount` INT(4) NULL,
  `dateofpayment` DATE NULL,
  `refund` INT(4) NULL,
  `invoicenum` INT(4) NOT NULL,
  `customerid` INT(4) NULL,
  PRIMARY KEY (`paymentid`),
  INDEX `FK30001_idx` (`customerid` ASC),
  INDEX `FK30002_idx` (`invoicenum` ASC),
  CONSTRAINT `FK30001`
    FOREIGN KEY (`customerid`)
    REFERENCES `Sales_Payment_And_Receivables`.`Customer` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK30002`
    FOREIGN KEY (`invoicenum`)
    REFERENCES `Sales_Payment_And_Receivables`.`invoice` (`invoicenum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
