-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 01:21:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hoadbofficial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoadbofficial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoadbofficial` DEFAULT CHARACTER SET utf8 ;
USE `hoadbofficial` ;

-- -----------------------------------------------------
-- Table `hoadbofficial`.`ref_coldays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`ref_coldays` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`ref_coldays` (
  `day` INT(2) NOT NULL,
  PRIMARY KEY (`day`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`ref_file_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`ref_file_types` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`ref_file_types` (
  `filetype` INT(4) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`filetype`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`files` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`files` (
  `fileid` INT(4) NOT NULL,
  `filename` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `filelocation` VARCHAR(45) NULL,
  `filetype` INT(4) NULL,
  `submitdate` DATE NULL,
  `uploader` VARCHAR(45) NULL,
  PRIMARY KEY (`fileid`),
  INDEX `FK02001_idx` (`filetype` ASC) VISIBLE,
  CONSTRAINT `FK02001`
    FOREIGN KEY (`filetype`)
    REFERENCES `hoadbofficial`.`ref_file_types` (`filetype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`supplier` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`supplier` (
  `name` VARCHAR(45) NOT NULL,
  `streetno` VARCHAR(45) NULL,
  `streetname` VARCHAR(45) NULL,
  `barangay` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `coordx` VARCHAR(45) NULL,
  `coordy` VARCHAR(45) NULL,
  `estabyear` DATE NULL,
  `website` VARCHAR(45) NULL,
  `subdname` VARCHAR(45) NULL,
  `aofincorporation_fileid` INT(4) NULL,
  `bylaws_fileid` INT(4) NULL,
  `minutesga_fileid` INT(4) NULL,
  `attendance_fileid` INT(4) NULL,
  `certification_fileid` INT(4) NULL,
  `coethics_fileid` INT(4) NULL,
  `regcolday` INT(2) NOT NULL,
  PRIMARY KEY (`name`),
  INDEX `FK01001_idx` (`regcolday` ASC) VISIBLE,
  INDEX `FK01002_idx` (`aofincorporation_fileid` ASC) VISIBLE,
  INDEX `FK01003_idx` (`bylaws_fileid` ASC) VISIBLE,
  INDEX `FK01004_idx` (`minutesga_fileid` ASC) VISIBLE,
  INDEX `FK01005_idx` (`attendance_fileid` ASC) VISIBLE,
  INDEX `FK01006_idx` (`certification_fileid` ASC) VISIBLE,
  INDEX `FK01007_idx` (`coethics_fileid` ASC) VISIBLE,
  CONSTRAINT `FK01001`
    FOREIGN KEY (`regcolday`)
    REFERENCES `hoadbofficial`.`ref_coldays` (`day`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01002`
    FOREIGN KEY (`aofincorporation_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01003`
    FOREIGN KEY (`bylaws_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01004`
    FOREIGN KEY (`minutesga_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01005`
    FOREIGN KEY (`attendance_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01006`
    FOREIGN KEY (`certification_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK01007`
    FOREIGN KEY (`coethics_fileid`)
    REFERENCES `hoadbofficial`.`files` (`fileid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`person` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`person` (
  `personid` INT(4) NOT NULL,
  `birthday` DATE NULL,
  `gender` ENUM('M', 'F') NULL,
  `email` VARCHAR(45) NULL,
  `fburl` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `undertaking` ENUM('Y', 'N') NULL,
  PRIMARY KEY (`personid`),
  UNIQUE INDEX `picture_UNIQUE` (`picture` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`products_catalog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`products_catalog` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`products_catalog` (
  `productid` INT(4) NOT NULL,
  `hoaname` VARCHAR(45) NULL,
  PRIMARY KEY (`productid`),
  INDEX `FK03001_idx` (`hoaname` ASC) VISIBLE,
  CONSTRAINT `FK03001`
    FOREIGN KEY (`hoaname`)
    REFERENCES `hoadbofficial`.`supplier` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK03002`
    FOREIGN KEY (`productid`)
    REFERENCES `hoadbofficial`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`person_mobile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`person_mobile` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`person_mobile` (
  `personid` INT(4) NOT NULL,
  `mobileno` INT(12) NOT NULL,
  PRIMARY KEY (`personid`, `mobileno`),
  CONSTRAINT `FKAA001`
    FOREIGN KEY (`personid`)
    REFERENCES `hoadbofficial`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`Customer` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`Customer` (
  `customerid` INT(4) NOT NULL,
  PRIMARY KEY (`customerid`),
  CONSTRAINT `FK06002`
    FOREIGN KEY (`customerid`)
    REFERENCES `hoadbofficial`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`person_complete_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`person_complete_name` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`person_complete_name` (
  `lastname` VARCHAR(45) NULL,
  `firstname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `personid` INT(4) NOT NULL,
  PRIMARY KEY (`personid`),
  CONSTRAINT `FK1001`
    FOREIGN KEY (`personid`)
    REFERENCES `hoadbofficial`.`person` (`personid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoadbofficial`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoadbofficial`.`products` ;

CREATE TABLE IF NOT EXISTS `hoadbofficial`.`products` (
  `productid` INT(4) NOT NULL,
  `product_type` ENUM('F', 'NF') NOT NULL,
  PRIMARY KEY (`productid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
