/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

/*
  Element Usage Report
    Input - 17 times
    NotGate - 8 times
    AndGate - 47 times
    OrGate - 14 times
    SevenSegDisplay - 3 times
    Output - 14 times
    NandGate - 1 times
*/

/*
  Usage Instructions and Tips
    Labels - Ensure unique label names and avoid using verilog keywords
    Warnings - Connect all optional inputs to remove warnings
*/

// Sample Testbench Code - Uncomment to use

/*
module TestBench();

  reg inp_0, inp_1, inp_2, inp_3, inp_4, inp_5, inp_6, inp_7, inp_8, W, X, Y, Z;

  wire A, B, C, D, E, F, G, out_A, out_B, out_C, out_D, out_E, out_F, out_g;

  Main DUT0(A, B, C, D, E, F, G, inp_0, inp_1, inp_2, inp_3, inp_4, inp_5, inp_6, inp_7, inp_8, W, X, Y, Z);

  \2126  DUT1(out_A, out_B, out_C, out_D, out_E, out_F, out_g, W, X, Y, Z);

  initial begin
    inp_0 = 0;
    inp_1 = 0;
    inp_2 = 0;
    inp_3 = 0;
    inp_4 = 0;
    inp_5 = 0;
    inp_6 = 0;
    inp_7 = 0;
    inp_8 = 0;
    W = 0;
    X = 0;
    Y = 0;
    Z = 0;

    #15
    $display("A = %b", A);
    $display("B = %b", B);
    $display("C = %b", C);
    $display("D = %b", D);
    $display("E = %b", E);
    $display("F = %b", F);
    $display("G = %b", G);
    $display("out_A = %b", out_A);
    $display("out_B = %b", out_B);
    $display("out_C = %b", out_C);
    $display("out_D = %b", out_D);
    $display("out_E = %b", out_E);
    $display("out_F = %b", out_F);
    $display("out_g = %b", out_g);

    #10
    $display("A = %b", A);
    $display("B = %b", B);
    $display("C = %b", C);
    $display("D = %b", D);
    $display("E = %b", E);
    $display("F = %b", F);
    $display("G = %b", G);
    $display("out_A = %b", out_A);
    $display("out_B = %b", out_B);
    $display("out_C = %b", out_C);
    $display("out_D = %b", out_D);
    $display("out_E = %b", out_E);
    $display("out_F = %b", out_F);
    $display("out_g = %b", out_g);

    $finish;

  end
endmodule

*/

module DE1 (out_A, out_B, out_C, out_D, out_E, out_F, out_g, W, X, Y, Z);
  output out_A,  out_B,  out_C,  out_D,  out_E,  out_F,  out_g;
  input W, X, Y, Z;
  wire \Z'_out , Sierra_out, G_out, Lima_out, C_out, India_out, F_out, Foxtrot_out, B_out, Alpha_out, D_out, A_out, Romeo_out, Quebec_out, Papa_out, Kilo_out, Charlie_out, \Y'_out , Oscar_out, November_out, E_out, Juliett_out, Delta_out, Mike_out, Hotel_out, \X'_out , Bravo_out, Golf_out, \W'_out ;
  assign \Z'_out  = ~Z;
  assign Sierra_out = Y & \Z'_out ;
  assign G_out = Romeo_out | Sierra_out | Hotel_out | Delta_out;
  assign out_g = G_out;
  
      always @ (*)
        $display("SevenSegDisplay:SevenSegDisplay_0.abcdefg. = %b%b%b%b%b%b%b}",
                 A_out, B_out, C_out, D_out, E_out, F_out, G_out);
  assign Lima_out = X & \Z'_out ;
  assign C_out = India_out | Juliett_out | Kilo_out | Lima_out | Charlie_out;
  assign out_C = C_out;
  assign India_out = W & Y & \Z'_out ;
  assign F_out = Oscar_out | Papa_out | Quebec_out | India_out;
  assign out_F = F_out;
  assign Foxtrot_out = \X'_out  & \Z'_out ;
  assign B_out = Foxtrot_out | Delta_out | Golf_out | Hotel_out;
  assign out_B = B_out;
  assign Alpha_out = X & Y & \Z'_out ;
  assign D_out = Bravo_out | Mike_out | Delta_out | Alpha_out;
  assign out_D = D_out;
  assign A_out = Alpha_out | Bravo_out | Charlie_out | Delta_out;
  assign out_A = A_out;
  assign Romeo_out = \W'_out  & \X'_out  & Z;
  assign Quebec_out = W & \Y'_out  & Z;
  assign Papa_out = \W'_out  & Y & Z;
  assign Kilo_out = \Y'_out  & Z;
  assign Charlie_out = \W'_out  & Z;
  assign \Y'_out  = ~Y;
  assign Oscar_out = \W'_out  & \X'_out  & \Y'_out ;
  assign November_out = \X'_out  & \Y'_out ;
  assign E_out = Bravo_out | November_out;
  assign out_E = E_out;
  assign Juliett_out = \W'_out  & \Y'_out ;
  assign Delta_out = W & \Y'_out ;
  assign Mike_out = \W'_out  & Y;
  assign Hotel_out = \W'_out  & Y;
  assign \X'_out  = ~X;
  assign Bravo_out = \W'_out  & \X'_out ;
  assign Golf_out = \W'_out  & X;
  assign \W'_out  = ~W;
endmodule
